name: code_rank
description: github code rank

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  json_annotation: ^1.0.0

dev_dependencies:
  cupertino_icons: ^0.1.2
  english_words: ^3.1.3
  http: '>=0.11.3+12'
  build_runner: ^0.10.0
  json_serializable: ^1.0.0

  # Used by tests. Not required to use `json_serializable`.
  path: ^1.5.1
  test: ^1.3.0


  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/ic_launcher.png
    - images/head.jpeg
    - images/ic_share_qq.png
    - images/ic_share_weixin.png

